# Generated by Django 2.0.2 on 2018-04-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='units',
        ),
        migrations.AddField(
            model_name='conversion',
            name='from_units',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='conversion',
            name='to_units',
            field=models.CharField(default='', max_length=100),
        ),
    ]
